name: chystka+server
description: A simple command-line application.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  aqueduct: ^3.3.0+1
  sqflite_common_ffi: any

dev_dependencies:
  pedantic: ^1.9.0

